### ISSUE TITLE
thanks for the basic font config

### ISSUE THREAD

**Issue by ejmg** [rwxr-xr-xis/dots#1]
hi there, stranger.

just wanted to say that it's been ~2-3 years since I've messed around with my arch system's font config files when suddenly most emojis broke on my system. out of any desire to find out why my old conf files got nuked and inability to get 2 other example confs working that I found online (and seemed up to date and to pass my sniff test), i found you comment a link to yours on reddit and it worked without issue.

thanks.

**Comment by rwxr-xr-xis** [comment]
Hey thanks a bunch!
